version: '3.3'

services:
  app:
    container_name: app_container
    build:
      context: .
      dockerfile: ./prod/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${POSTGRES_USER_NEXT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_NEXT}
      POSTGRES_DB: ${POSTGRES_DB}
      AUTH_SECRET: ${AUTH_SECRET} 
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}

  db:
    image: postgres:17
    container_name: postgre_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

volumes:
  db-data: